# Dockerfile.nginx
FROM nginx:stable

# Копируем наш конфигурационный файл
COPY nginx.conf /etc/nginx/nginx.conf

# Устанавливаем рабочую директорию
WORKDIR /usr/share/nginx/html

# Копируем все статические файлы в нужную директорию
COPY ./.next .

# Открываем порт 80
EXPOSE 80