version: '3.8'

services:
  app:
    build: .
    container_name: app
    environment:
      - NODE_ENV=production

  nginx:
    # image: nginx:alpine
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      # Для HTTPS порт
      - "443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    logging:
      options:
        max-size: "10m"
        max-file: "3"
