version: '3.9'

services:
  nextapp:
    container_name: nextapp
    restart: always
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'

  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextapp
