name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Lint and fix
        run: yarn lint --fix
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test
